Git Workshop 2023 Assignment
ITClubPulchowk/First-Contribution pull request #4
Opened 2023-07-29 14:42 UTC by rpandox

2023-07-29 16:21 UTC, SusheelThapa commented on 2023/assignments/Roshan/Roshan.md
> +
remove redundant space at last

2023-07-29 16:23 UTC, SusheelThapa commented
![image](https://github.com/ITClubPulchowk/First-Contribution/assets/83917129/efdcf799-1b75-4d27-bcef-3997a302cf2f)

Upto 9 number timile lekeko format right xa,
Ani 10 pachi tyo Description ma **Description** ako xan, tyo update gara...

2023-07-29 18:30 UTC, rpandox commented
Resolved all the problems 
Can you check them again 
```
@SusheelThapa 
Thankyou for the feedback
```

2023-07-30 01:40 UTC, SusheelThapa requested changes

2023-07-30 01:40 UTC, SusheelThapa commented on 2023/assignments/Roshan/Roshan.md
> +***Description** :
One asterisk is more...

2023-07-30 01:40 UTC, SusheelThapa commented on 2023/assignments/Roshan/Roshan.md
> +### <p align='center'>`Roshan Pandey`</p>
Remove back tick(**\`**) from the name.

2023-07-30 01:40 UTC, SusheelThapa commented on 2023/assignments/Roshan/Roshan.md
> +
![mistake](https://github.com/ITClubPulchowk/First-Contribution/assets/83917129/c0af9edb-1495-482f-8628-317ca50b434c)

2023-07-30 02:18 UTC, rpandox commented
Can you please check again I updated the file 
@SusheelThapa

2023-07-30 02:21 UTC, SusheelThapa commented on 2023/assignments/Roshan/Roshan.md
> +### <p align='center'>`Roshan Pandey`</p>
You haven't resolve this change.

2023-07-30 02:22 UTC, SusheelThapa requested changes

2023-07-30 02:22 UTC, SusheelThapa commented on 2023/assignments/Roshan/Roshan.md
> +
Indent alignment mistake xa hai 17 ma
@rpandox

2023-07-30 02:24 UTC, SusheelThapa commented
Ani tyo name ma backtick wala ne solve gara @rpandox 
![image](https://github.com/ITClubPulchowk/First-Contribution/assets/83917129/dca89c22-2a40-449f-8140-79c5bd9600f2)

2023-07-30 02:38 UTC, SusheelThapa requested changes

2023-07-30 02:38 UTC, SusheelThapa commented on 2023/assignments/Roshan/Roshan.md
> +        alt="your_name"
In the *alt='your_name'*, replace with your name.

2023-07-30 02:38 UTC, SusheelThapa commented on 2023/assignments/Roshan/Roshan.md
> +        alt="your_name"
In the *alt='your_name'*, replace with your name.

2023-07-30 02:38 UTC, SusheelThapa commented on 2023/assignments/Roshan/Roshan.md
> +        alt="your_name"
In the *alt='your_name'*, replace with your name.

2023-07-30 02:38 UTC, SusheelThapa commented on 2023/assignments/Roshan/Roshan.md
> +        alt="your_name"
In the *alt='your_name'*, replace with your name.

2023-07-30 02:55 UTC, rpandox commented
I think this is the final change 
@SusheelThapa

2023-07-30 03:20 UTC, SusheelThapa approved these changes

2023-07-30 03:25 UTC, merged