Git Workshop 2023 Assignment!
ITClubPulchowk/First-Contribution pull request #9
Opened 2023-07-30 16:06 UTC by aadrkdk

2023-07-30 18:00 UTC, suravshrestha requested changes

2023-07-30 18:00 UTC, suravshrestha commented on 2023/assignments/aadarsha/aadarsha.md
> +    <a href="#" target="blank"
@aadrkdk, if you have social media links, kindly replace them. Otherwise, remove any existing links.

2023-07-31 02:04 UTC, aadrkdk commented on 2023/assignments/aadarsha/aadarsha.md
> +    <a href="#" target="blank"
@suravshrestha, I will do it.

2023-07-31 02:24 UTC, aadrkdk commented
I have updated my assignments.



On Sun, 30 Jul 2023 at 23:45, Surav Shrestha ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In 2023/assignments/aadarsha/aadarsha.md
> <https://github.com/ITClubPulchowk/First-Contribution/pull/9#discussion_r1278598246>
> :
>
> > @@ -0,0 +1,93 @@
> +# <p align='center'>Git Workshop 2023 <p>
> +
> +### <p align='center'>Aadarsha Khadka</p>
> +
> +<p align="center">
> +    <a href="#" target="blank"
>
> @aadrkdk <https://github.com/aadrkdk>, if you have social media links,
> kindly replace them. Otherwise, remove any existing links.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ITClubPulchowk/First-Contribution/pull/9#pullrequestreview-1553677213>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AY75ACH2QF7HZWASIAE2AVTXS2OMPANCNFSM6AAAAAA25I5CVA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-07-31 06:14 UTC, merged

2023-07-31 06:16 UTC, suravshrestha commented
@aadrkdk, thank you for your active participation in the workshop. Your contributions are highly appreciated.